server:
  port: 8888

spring:
  main:
    web-application-type: reactive
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: service-client-route
          uri: lb://SERVICE-CLIENT
          predicates:
            - Path=/api/clients/**
        - id: service-car-route
          uri: lb://SERVICE-CAR
          predicates:
            - Path=/api/car/**

    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost